project:
  name: MyFirstCIProject
  version: 1.0.0
  description: This is a basic configuration file for my first CI/CD project.
  author: Sina Sami

on:
  push:
    branches:
      - main

jobs:
  name:
    My_First_CI_Project:
      runs-on: ubuntu-latest

      steps:
        - name: Echo
          run: echo test
